In [24]:
import numpy as np # 

In [13]:
np.array([1,2,3]) #

array([1, 2, 3])

In [26]:
a=np.array([1,2,3]) # Bir NumPy dizisini atama işlemi için kullanılır

In [17]:
dizi=np.array([1,2,3,3.14])
dizi

array([1.  , 2.  , 3.  , 3.14])

In [28]:
dizi=np.array([1,2,3,3.14],dtype=int)
dizi

array([1, 2, 3, 3])

In [30]:
birboyut=np.array([1,2,3])  # bir boyutlu dizi oluşturur
birboyut

array([1, 2, 3])

In [32]:
ikiboyut = np.array([[1,2,3], [4,5,6]]) #: İki boyutlu dizi oluşturmak için kullanılır
ikiboyut

array([[1, 2, 3],
       [4, 5, 6]])