In [9]:
import numpy as np #numpy küyüphanesini np takma adı ile projeye dahil ediyoruz

In [5]:
dizi= np.full((4,3),5) #4(satır),3(sütün) ve 5 sayısıda içindeki sayıyı belirtir
dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [7]:
#yeni bir numpy dizisi oluşturuyoruz
np.array([1,2,3])

array([1, 2, 3])

In [17]:
#oluşturduğumuz diziyi bir değişkene aktırıyoruz
dizi=np.array(["elma","erik","iğne"])

In [15]:
dizi

array(['elma', 'erik', 'iğne'], dtype='<U4')

In [19]:
dizi=np.array([1,2,3])

In [21]:
dizi=np.array([1,2,3.14])

In [23]:
dizi.dtype #dizinin değişken türünü verir. nupmy dizelerinde elemanların hepsi aynı türdendir

dtype('float64')

In [25]:
dizi=np.array([1,23.14], dtype=int)

**Numpy ile farklı boyutlarda dizi oluşturma**

In [28]:
#bir boyutlu dizi oluşturma
birboyut=np.array([1,2,3,4])
#iki boyutlu dizi oluşturma
ikiboyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [30]:
birboyut

array([1, 2, 3, 4])

In [32]:
ikiboyut

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Numpy Yer Tutucular**

In [35]:
np.zeros(7) # 7 sıfırdan oluşan tek boyutlu dizi oluşturur

array([0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.zeros((2,3), dtype=int) #* sıfırdan oluşan 2 boyutlu int dizi oluşturur

array([[0, 0, 0],
       [0, 0, 0]])

In [41]:
np.ones(3)

array([1., 1., 1.])

In [43]:
np.full((4,3),5)#5 sayısından oluşan2*3 lük dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [45]:
np.arange(2,22,5) #5 sayısından oluşan 2*3 lük dizi

array([ 2,  7, 12, 17])

In [47]:
np.linspace(2,10,num=7) #başlangıç ve bitiş değeri aralığında belirtilen miktarda eşit aralık

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [49]:
np.random.randint(0,10,5) #0-10 aralığında rastgele sayıdan oluşan bir boyutlu dizi 

array([3, 6, 2, 5, 7])

In [53]:
np.random.randint(0,10,(5,2)) #0-10 aralığında 5*2 rastgele sayıdan oluşan 2 boyutlu dizi

array([[4, 1],
       [9, 2],
       [2, 4],
       [9, 5],
       [0, 5]])

**Diziler ile ilgili işlemler**

In [58]:
#dizilerin elaman sayısını öğrenmek için shope komutu kullanır
dizi=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
dizi.shape

(3, 4)

In [62]:
#ndim dizi boyutunu öğrenmek için shabe komutu kullanır
dizi.ndim

2

In [64]:
#size dizidekş toplam eleman sayısını gösterir
dizi.size

12

In [66]:
#dizideki her bir eleman bayt cinsinden değerini verir
dizi.itemsize

4

In [77]:
dizi=np.random.randint(0, 100, size=(5, 7))
dizi

array([[89,  4, 97, 47, 58, 56, 49],
       [39, 82, 93,  3, 52, 98, 67],
       [46,  2, 23, 32, 59, 99, 42],
       [85, 13, 68, 99, 37, 82, 24],
       [92, 40, 59, 29, 44, 98, 62]])