In [15]:
 #Temel kütüphaneler içe aktarılır.
import numpy as np
import pandas as pd 
from sklearn import linear_model

In [16]:
# Veri seti yüklenir. 
data = pd.read_csv('homeprices.csv')
# Veriye göz atılır.
data.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [17]:
# Sütun adları Türkçeye çevrilmiştir.
data.rename(columns = {'area':'alan', 'bedrooms':'oda_sayisi','age':'yasi', 'price':'fiyati'}, inplace = True)
# Veri setine göz atılır.
data.head()

alan  oda_sayisi  yasi  fiyati
0  2600         3.0    20  550000
1  3000         4.0    15  565000
2  3200         NaN    18  610000
3  3600         3.0    30  595000
4  4000         5.0     8  760000

In [18]:
# Veri türleri ve eksik veri bilgisi görüntülenir.
data.info()
# Eksik veri ortanca değer ile tamamlanır.
# Veri setinin özelliğine göre farklı yöntemler kullanılabilir. 
median_oda_sayisi = data['oda_sayisi'].median()
median_oda_sayisi

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   alan        6 non-null      int64  
 1   oda_sayisi  5 non-null      float64
 2   yasi        6 non-null      int64  
 3   fiyati      6 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 324.0 bytes


4.0

In [19]:
# Eksik veri ortanca değer ile tamamlanır.
# Veri setinin özelliğine göre farklı yöntemler kullanılabilir. 
median_oda_sayisi = data['oda_sayisi'].median()
median_oda_sayisi
data.oda_sayisi = data.oda_sayisi.fillna(median_oda_sayisi)
data

alan  oda_sayisi  yasi  fiyati
0  2600         3.0    20  550000
1  3000         4.0    15  565000
2  3200         4.0    18  610000
3  3600         3.0    30  595000
4  4000         5.0     8  760000
5  4100         6.0     8  810000

In [21]:
# Çoklu doğrusal regresyon modeli eğitilir.
# Özellik olarak alan, oda_sayisi ve yasi sütunları seçilir.
# Tahmin edilecek değişken olarak fiyat sütunu belirlenir.
reg = linear_model.LinearRegression() 
reg.fit(data[['alan', 'oda_sayisi', 'yasi']], data.fiyati)

LinearRegression()

In [22]:
# Regresyon denklemi sabit ve katsayılar.
print('Sabit (bias): \n', reg.intercept_)
print('Katsayılar: \n', reg.coef_)

Sabit (bias): 
 221323.00186540408
Katsayılar: 
 [  112.06244194 23388.88007794 -3231.71790863]


In [23]:
# Model kullanılarak tahminler yapılır.
reg_pred = reg.predict(data[['alan', 'oda_sayisi', 'yasi']])

In [24]:
# Model değerlendirme metrikleri içe aktarılır.
from sklearn.metrics import mean_squared_error, r2_score
# Ortalama Kare Hata
print("Ortalama Kare Hata: %.2f" % mean_squared_error(data.fiyati, reg_pred))
# R Kare: 1 mükemmel tahmin.
print("R Kare: %.2f" % r2_score(data.fiyati, reg_pred))

Ortalama Kare Hata: 446305128.22
R Kare: 0.96


In [25]:
reg.predict([[3000,3,40]])

C:\Users\PC\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [26]:
array([498408.25158031])

NameError: name 'array' is not defined